import {cp,mkdir,rm,readdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';

// Production is static. This build only packages files and fingerprints the offline cache.
await rm('dist',{recursive:true,force:true});
await mkdir('dist',{recursive:true});
await cp('public','dist',{recursive:true});
const files=(await readdir('dist',{recursive:true})).filter(p=>/\.(?:js|css|html|png|svg|webmanifest|json|wav)$/.test(p)&&p!=='sw.js').sort();
const fingerprint=createHash('sha256');
for(const file of files){fingerprint.update(file);fingerprint.update(await readFile(join('dist',file)));}
const hash=fingerprint.digest('hex').slice(0,12);
const assets=['./',...files.map(p=>'./'+p)];
const worker=`// Generated by scripts/build.mjs. Scope-aware for GitHub Pages project paths.
const CACHE='chrono-circuit-v9-${hash}';
const ASSETS=${JSON.stringify(assets)};
const scope=new URL(self.registration.scope).pathname;
const prefix='chrono-circuit:'+scope+':';
const cacheName=prefix+CACHE;
const paths=new Set(ASSETS.map(path=>new URL(path,self.registration.scope).pathname));
self.addEventListener('install',event=>event.waitUntil(caches.open(cacheName).then(cache=>cache.addAll(ASSETS))));
// Activate after old tabs close, avoiding a new module graph halfway through a saved run.
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(prefix)&&k!==cacheName).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==self.location.origin||!paths.has(url.pathname))return;
 event.respondWith((async()=>{
  const cache=await caches.open(cacheName);
  const cached=await cache.match(event.request,{ignoreSearch:true});
  if(cached)return cached;
  return fetch(event.request);
 })());
});
`;
await writeFile('dist/sw.js',worker);
await writeFile('dist/.nojekyll','');
console.log(`Built ${files.length} files; offline cache ${hash}.`);
